# Generated by Django 2.1.7 on 2019-02-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avialable',
            new_name='available',
        ),
    ]
